name: Docker Build CI        # Workflow name (visible in UI)

on:                         # Trigger
  push:
    branches:
      - main                # Runs when code is pushed to main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner (VM)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Pulls repo code into runner
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      -  name: Set up QEMU
         uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mahijs/app:latest
          
      #- name: Build Docker image
      #  run: docker build -t ${{ secrets.DOCKER.USERNAME }}/my-nginx-app:latest .
      #- name: Docker push
      #  run: docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx-app:latest
        # Runs docker build command
